apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: python app that displays the current time, hostname, and message
  annotations:
    github.com/project-slug: Itsmeashok/${{values.app_name}}
spec:
  type: service
  owner: development
  lifecycle: experimental